;; copy "sample.test-settings.scm" to ".test-settings.scm"
;; create 2 twitter test account and fill the following sexp.
;; oauth-token will be generated by twitauth.
(
 (user . "***YOUR USERNAME***")
 (password . "***YOUR PASSWORD***")
 (consumer-key . "***YOUR CONSUMER KEY***")
 (consumer-secret-key . "***YOUR CONSUMER SECRET KEY***")

 ;; temporary settings
 (oauth-token . ((consumer-key        . "")
                 (consumer-secret     . "")
                 (access-token        . "")
                 (access-token-secret . "")))

 (user2 . "***YOUR SECOND USERNAME***")
 (password2 . "***YOUR SECOND PASSWORD***")

 (oauth-token2 . ((consumer-key        . "")
				  (consumer-secret     . "")
				  (access-token        . "")
				  (access-token-secret . "")))
 )
