(define-module net.twitter.auth.persistent
  (use net.twitter.core)
  (export
   write-credential! read-credential))
(select-module net.twitter.auth.persistent)

;; ## Write oauth credential SEXP to FILE
;; Save credential generated by `net/twitauth.scm` script
(define (write-credential! sexp file)
  (with-output-to-file file
    (^[] (write sexp)))
  (sys-chmod file #o600))

;; ## Read oauth credential from FILE
;; -> <twitter-cred>
(define (read-credential file)
  (let1 sexp (with-input-from-file file read)
    (make <twitter-cred>
      :consumer-key         (assq-ref sexp 'consumer-key)
      :consumer-secret      (assq-ref sexp 'consumer-secret)
      :access-token         (assq-ref sexp 'access-token)
      :access-token-secret  (assq-ref sexp 'access-token-secret))))
